name: ci-golang-workflow
on: 
 push:
  branches:
    - main
strategy:
  matrix:
    go: ['1.14', '1.15']
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #faz checkout no ubuntu
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go test
      - run: go run math.go